# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daniel/git/ogle

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daniel/git/ogle

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/git/ogle/CMakeFiles /home/daniel/git/ogle/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/git/ogle/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f ogle/CMakeFiles/doc.dir/build.make ogle/CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named ogle

# Build rule for target.
ogle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ogle
.PHONY : ogle

# fast build rule for target.
ogle/fast:
	$(MAKE) -f ogle/CMakeFiles/ogle.dir/build.make ogle/CMakeFiles/ogle.dir/build
.PHONY : ogle/fast

#=============================================================================
# Target rules for targets named qt-application

# Build rule for target.
qt-application: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qt-application
.PHONY : qt-application

# fast build rule for target.
qt-application/fast:
	$(MAKE) -f applications/qt/CMakeFiles/qt-application.dir/build.make applications/qt/CMakeFiles/qt-application.dir/build
.PHONY : qt-application/fast

#=============================================================================
# Target rules for targets named assimp-test

# Build rule for target.
assimp-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assimp-test
.PHONY : assimp-test

# fast build rule for target.
assimp-test/fast:
	$(MAKE) -f applications/test/CMakeFiles/assimp-test.dir/build.make applications/test/CMakeFiles/assimp-test.dir/build
.PHONY : assimp-test/fast

#=============================================================================
# Target rules for targets named factory

# Build rule for target.
factory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 factory
.PHONY : factory

# fast build rule for target.
factory/fast:
	$(MAKE) -f applications/test/CMakeFiles/factory.dir/build.make applications/test/CMakeFiles/factory.dir/build
.PHONY : factory/fast

#=============================================================================
# Target rules for targets named hdr-test

# Build rule for target.
hdr-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hdr-test
.PHONY : hdr-test

# fast build rule for target.
hdr-test/fast:
	$(MAKE) -f applications/test/CMakeFiles/hdr-test.dir/build.make applications/test/CMakeFiles/hdr-test.dir/build
.PHONY : hdr-test/fast

#=============================================================================
# Target rules for targets named instancing-test

# Build rule for target.
instancing-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 instancing-test
.PHONY : instancing-test

# fast build rule for target.
instancing-test/fast:
	$(MAKE) -f applications/test/CMakeFiles/instancing-test.dir/build.make applications/test/CMakeFiles/instancing-test.dir/build
.PHONY : instancing-test/fast

#=============================================================================
# Target rules for targets named mesh-animation-test

# Build rule for target.
mesh-animation-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mesh-animation-test
.PHONY : mesh-animation-test

# fast build rule for target.
mesh-animation-test/fast:
	$(MAKE) -f applications/test/CMakeFiles/mesh-animation-test.dir/build.make applications/test/CMakeFiles/mesh-animation-test.dir/build
.PHONY : mesh-animation-test/fast

#=============================================================================
# Target rules for targets named transparency-test

# Build rule for target.
transparency-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 transparency-test
.PHONY : transparency-test

# fast build rule for target.
transparency-test/fast:
	$(MAKE) -f applications/test/CMakeFiles/transparency-test.dir/build.make applications/test/CMakeFiles/transparency-test.dir/build
.PHONY : transparency-test/fast

#=============================================================================
# Target rules for targets named volume-test

# Build rule for target.
volume-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 volume-test
.PHONY : volume-test

# fast build rule for target.
volume-test/fast:
	$(MAKE) -f applications/test/CMakeFiles/volume-test.dir/build.make applications/test/CMakeFiles/volume-test.dir/build
.PHONY : volume-test/fast

#=============================================================================
# Target rules for targets named ogle-video-player

# Build rule for target.
ogle-video-player: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ogle-video-player
.PHONY : ogle-video-player

# fast build rule for target.
ogle-video-player/fast:
	$(MAKE) -f applications/video-player/CMakeFiles/ogle-video-player.dir/build.make applications/video-player/CMakeFiles/ogle-video-player.dir/build
.PHONY : ogle-video-player/fast

#=============================================================================
# Target rules for targets named ogle-texture-updater

# Build rule for target.
ogle-texture-updater: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ogle-texture-updater
.PHONY : ogle-texture-updater

# fast build rule for target.
ogle-texture-updater/fast:
	$(MAKE) -f applications/texture-updater/CMakeFiles/ogle-texture-updater.dir/build.make applications/texture-updater/CMakeFiles/ogle-texture-updater.dir/build
.PHONY : ogle-texture-updater/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... doc"
	@echo "... ogle"
	@echo "... qt-application"
	@echo "... assimp-test"
	@echo "... factory"
	@echo "... hdr-test"
	@echo "... instancing-test"
	@echo "... mesh-animation-test"
	@echo "... transparency-test"
	@echo "... volume-test"
	@echo "... ogle-video-player"
	@echo "... ogle-texture-updater"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

