#ifndef REGEN_SilhouetteMesh_H
#define REGEN_SilhouetteMesh_H

#include <regen/objects/mesh.h>
#include "regen/objects/lod/silhouette-generator.h"

namespace regen {
	/**
	 * A mesh that generates a silhouette from a texture atlas.
	 * The silhouette is generated by a SilhouetteGenerator and stored in a texture.
	 * The mesh can be used to render the silhouette as a 3D object.
	 */
	class SilhouetteMesh : public Mesh {
	public:
		struct Config {
			/** Configuration for the silhouette generator. */
			SilhouetteConfig silhouette;
			/** scaling for the position attribute. */
			Vec3f posScale = Vec3f::one();
			/** cube xyz rotation. */
			Vec3f rotation = Vec3f::zero();
			/** scaling vector for TEXCO_MODE_UV. */
			Vec2f texcoScale = Vec2f::one();
			/** texture coordinate mode. */
			bool hasUV = true;
			/** generate normal attribute ?. */
			bool hasNormal = false;
			/** generate tangent attribute ?. */
			bool hasTangent = false;
			/** Buffer usage hints. */
			ClientAccessMode accessMode = BUFFER_CPU_WRITE;
			BufferUpdateFlags updateHints = BufferUpdateFlags::NEVER;
			BufferMapMode mapMode = BUFFER_MAP_DISABLED;

			Config();
		};

		explicit SilhouetteMesh(const ref_ptr<Texture2D> &silhouetteTex, const Config &cfg = Config());

		void setSilhouetteGenerator(const ref_ptr<SilhouetteGenerator> &g);

		void updateSilhouette();

		void updateAttributes();

		const std::vector<std::vector<Vec4f>>& silhouetteUVRects() const { return silhouetteUVRects_; }

		/**
		 * Load an impostor billboard from a scene input node.
		 * @param ctx the loading context
		 * @param input the scene input node
		 * @return the impostor billboard
		 */
		static ref_ptr<SilhouetteMesh> load(LoadingContext &ctx, scene::SceneInputNode &input);

	protected:
		const Config silhouetteCfg_;

		// silhouette texture with alpha channel
		ref_ptr<Texture2D> silhouetteTex_;
		// silhouette data generator
		ref_ptr<SilhouetteGenerator> silhouetteGenerator_;
		// per-LOD silhouette data
		std::vector<std::vector<Vec4f>> silhouetteUVRects_;

		ref_ptr<ShaderInput3f> pos_;
		ref_ptr<ShaderInput3f> nor_;
		ref_ptr<ShaderInput4f> tan_;
		ref_ptr<ShaderInput> uv_;
		ref_ptr<ShaderInput> indices_;

		void generateLODLevel(uint32_t lodLevel, uint32_t vertexOffset, uint32_t indexOffset);
	};
} // namespace

#endif /* REGEN_SilhouetteMesh_H */
